version: "3"

services:
  rclone:
    build:
      context: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    volumes:
      - './config/rclone:/config/rclone'
      - '~/Documents:/data'
    cpus: 0.5
    mem_limit: 512m
